[package]
name = "wordles"
version = "1.0.0"
authors = ["David Graham <david.malcom.graham@gmail.com>"]
description = "A Wordle solver."
repository = "https://github.com/dgraham/wordles"
license = "MIT"
edition = "2024"

[dependencies]
getopts = "0.2.24"
lmdb = "0.8.0"

[profile.release]
strip = true
panic = "abort"
